DROP TABLE "EMOTICON";

CREATE TABLE "EMOTICON" (
	"EMOTICON_NO"		NUMBER					NOT NULL,
	"REPLY_NO"			NUMBER					NOT NULL,
	"EMOTICON_CODE"		CHAR(2)					NOT NULL,
	"EMOTICON_COUNT"	NUMBER		DEFAULT 0	NOT NULL
);

-- "EMOTICON" 주석 설정
COMMENT ON COLUMN "EMOTICON"."EMOTICON_NO" IS '이모티콘번호(SEQ_EMOTICON_NO)';
COMMENT ON COLUMN "EMOTICON"."REPLY_NO" IS '댓글번호(SEQ_REPLY_NO)';
COMMENT ON COLUMN "EMOTICON"."EMOTICON_CODE" IS 'CD_EMOTICON.EMOTICON_CODE';
COMMENT ON COLUMN "EMOTICON"."EMOTICON_COUNT" IS '이모티콘 눌린 횟수';

-- 외래키 설정
ALTER TABLE "EMOTICON" ADD CONSTRAINT "PK_EMOTICON" PRIMARY KEY ("EMOTICON_NO");
ALTER TABLE "EMOTICON" ADD CONSTRAINT "FK_REPLY_TO_EMOTICON_1" FOREIGN KEY ("REPLY_NO") REFERENCES "REPLY";
ALTER TABLE "EMOTICON" ADD CONSTRAINT "FK_CD_EMOTICON_TO_EMOTICON_1" FOREIGN KEY ("EMOTICON_CODE") REFERENCES "CD_EMOTICON";

------------------------------------------------------------------------------------------------------------------------------------

DROP TABLE "CD_EMOTICON";

CREATE TABLE "CD_EMOTICON" (
	"EMOTICON_CODE"	CHAR(2)				NOT NULL,
	"EMOTICON_TYPE"	VARCHAR(100)		NOT NULL
);

COMMENT ON COLUMN "CD_EMOTICON"."EMOTICON_CODE" IS 'E1 ~ E5';

ALTER TABLE "CD_EMOTICON" ADD CONSTRAINT "PK_CD_EMOTICON" PRIMARY KEY ("EMOTICON_CODE");

