DROP TABLE "FEEDBACK";

CREATE TABLE "FEEDBACK" (
	"FEEDBACK_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"FEEDBACK_CONTENT"	CLOB		NULL,
	"FEEDBACK_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ADMIN_NO"	NUMBER		NULL,
	"ADMIN_COMMENT"	VARCHAR2(4000)		NULL,
	"CONFIRM_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"CONFIRM_DATE"	DATE		NULL
);

COMMENT ON COLUMN "FEEDBACK"."FEEDBACK_NO" IS '의견번호(SEQ_OPINION_NO)';

COMMENT ON COLUMN "FEEDBACK"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "FEEDBACK"."FEEDBACK_CONTENT" IS '의견내용';

COMMENT ON COLUMN "FEEDBACK"."FEEDBACK_DATE" IS '작성일';

COMMENT ON COLUMN "FEEDBACK"."ADMIN_NO" IS '처리한관리자(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "FEEDBACK"."ADMIN_COMMENT" IS '관리자의견';

COMMENT ON COLUMN "FEEDBACK"."CONFIRM_FL" IS 'N: 처리중, Y:처리완료';

COMMENT ON COLUMN "FEEDBACK"."CONFIRM_DATE" IS '처리일시';

ALTER TABLE "FEEDBACK" ADD CONSTRAINT "PK_FEEDBACK" PRIMARY KEY (
	"FEEDBACK_NO"
);

ALTER TABLE "FEEDBACK" ADD CONSTRAINT "FK_MEMBER_TO_FEEDBACK_USER" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "FEEDBACK" ADD CONSTRAINT "FK_MEMBER_TO_FEEDBACK_ADMIN" FOREIGN KEY (
	"ADMIN_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


-- SEQ_FEEDBACK_NO 생성
CREATE SEQUENCE SEQ_FEEDBACK_NO NOCACHE;

----------------------------------------------------------------------------------------

-- FEEDBACK 샘플 데이터 삽입
BEGIN
   FOR I IN 1..100 LOOP
      INSERT INTO "FEEDBACK" 
      VALUES(
      	SEQ_FEEDBACK_NO.NEXTVAL, 		-- 의견번호
		CEIL(DBMS_RANDOM.VALUE(0,300)),  -- 회원번호
		SEQ_FEEDBACK_NO.CURRVAL || '번째 피드백 내용 입니다.', -- 내용
		DEFAULT, -- 접수일시(SYSDATE)
		NULL, -- 처리자
		NULL, -- 처리내용
		DEFAULT, -- 처리상태(기본값:'N')
		NULL -- 처리일시
      );
   END LOOP;
END;

COMMIT;

SELECT * FROM "FEEDBACK" ORDER BY feedback_no desc;


-- 조회
SELECT FEEDBACK_NO, MEMBER_NO, FEEDBACK_CONTENT, ADMIN_NO, ADMIN_COMMENT, CONFIRM_FL, MEMBER_NAME,
			TO_CHAR(FEEDBACK_DATE, 'YYYY-MM-DD') FEEDBACK_DATE,
			TO_CHAR(CONFIRM_DATE, 'YYYY-MM-DD HH24:MI:SS') CONFIRM_DATE
FROM "FEEDBACK" JOIN "MEMBER" USING(MEMBER_NO)
WHERE FEEDBACK_NO = 1;


-- 처리완료 처리
UPDATE "FEEDBACK" SET
CONFIRM_FL = 'Y', ADMIN_NO = 1, ADMIN_COMMENT ='1번째 피드백 처리내용입니다.', CONFIRM_DATE=SYSDATE
WHERE FEEDBACK_NO=1;

UPDATE "FEEDBACK" SET
CONFIRM_FL = 'Y', ADMIN_NO = 1, ADMIN_COMMENT ='99번째 피드백 처리내용입니다.', CONFIRM_DATE=SYSDATE
WHERE FEEDBACK_NO=99;

ROLLBACK;
COMMIT;