DROP TABLE "FRIEND";

CREATE TABLE "FRIEND" (
    "FRIEND_NO" NUMBER      NOT NULL,
    "FRIEND_SENDER" NUMBER      NOT NULL,
    "FRIEND_RECIVER"    NUMBER      NOT NULL,
    "FRIEND_FL" CHAR(1) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN "FRIEND"."FRIEND_NO" IS '요청번호(SEQ_FRIEND_REQ_NO)';

COMMENT ON COLUMN "FRIEND"."FRIEND_SENDER" IS '회원번호(SEQ_MEMBER_NO), 신청한회원';

COMMENT ON COLUMN "FRIEND"."FRIEND_RECIVER" IS '회원번호(SEQ_MEMBER_NO),신청받은회원';

COMMENT ON COLUMN "FRIEND"."FRIEND_FL" IS '친구여부(N:신청중, Y:친구상태)';

ALTER TABLE "FRIEND" ADD CONSTRAINT "PK_FRIEND" PRIMARY KEY (
    "FRIEND_NO"
);

ALTER TABLE "FRIEND" ADD CONSTRAINT "FK_MEMBER_TO_FRIEND_1" FOREIGN KEY (
    "FRIEND_SENDER"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

ALTER TABLE "FRIEND" ADD CONSTRAINT "FK_MEMBER_TO_FRIEND_2" FOREIGN KEY (
    "FRIEND_RECIVER"
)
REFERENCES "MEMBER" (
    "MEMBER_NO"
);

CREATE SEQUENCE SEQ_FRIEND_NO NOCACHE; --시퀀스 생성 
SELECT * FROM "FRIEND"; -- 친구신청 조회 

SELECT * FROM "MEMBER"; -- 맴버 조회

INSERT INTO "FRIEND" VALUES(SEQ_FRIEND_NO.NEXTVAL,2,5, DEFAULT); --친구신청 인설트
DELETE FROM "FRIEND" WHERE FRIEND_NO = 1; -- 친구신청 삭제