-- "MEMBER" 테이블 생성
DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEMBER_NO"			NUMBER		NOT NULL,
	"MEMBER_EMAIL"		VARCHAR2(300)		NOT NULL,
	"MEMBER_PW"			VARCHAR2(300)		NOT NULL,
	"MEMBER_NAME"		VARCHAR2(60)		NOT NULL,
	"MEMBER_TEL"		CHAR(11)		NULL,
	"MEMBER_CODE"		CHAR(1)			DEFAULT 'N'	NOT NULL,
	"ENROLL_DATE"		DATE			DEFAULT SYSDATE	NOT NULL,
	"DISABLE_DATE"		DATE		NULL,
	"DELETE_DATE"		DATE		NULL,
	"SET_FRIEND_REQ"	CHAR(1)		DEFAULT 'Y'	NOT NULL,
	"SET_FEED_AUTH"		CHAR(1)		DEFAULT 'Y'	NOT NULL,
	"SET_AL_FRIEND_REQ"	CHAR(1)		DEFAULT 'Y'	NOT NULL,
	"SET_AL_REQ_ACCEPT"	CHAR(1)		DEFAULT 'Y'	NOT NULL,
	"SET_AL_TAG"		CHAR(1)		DEFAULT 'Y'	NOT NULL,
	"SET_AL_REPLY"		CHAR(1)		DEFAULT 'Y'	NOT NULL,
	"SET_AL_LIKE"		CHAR(1)		DEFAULT 'Y'	NOT NULL,
	"SET_AL_SHARE"		CHAR(1)		DEFAULT 'Y'	NOT NULL,
	"SET_AL_FEED"		CHAR(1)		DEFAULT 'Y'	NOT NULL
);

-- 주석 설정
COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '이름';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_CODE" IS '계정분류';
COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '가입일';
COMMENT ON COLUMN "MEMBER"."DISABLE_DATE" IS '비활성화일';
COMMENT ON COLUMN "MEMBER"."DELETE_DATE" IS '탈퇴일';
COMMENT ON COLUMN "MEMBER"."SET_FRIEND_REQ" IS '친구요청(N:OFF, Y:ON)';
COMMENT ON COLUMN "MEMBER"."SET_FEED_AUTH" IS '개인피드설정(N:OFF, Y:ON)';
COMMENT ON COLUMN "MEMBER"."SET_AL_FRIEND_REQ" IS '친구요청알림(N:OFF, Y:ON)';
COMMENT ON COLUMN "MEMBER"."SET_AL_REQ_ACCEPT" IS '친구신청수락알림(N:OFF, Y:ON)';
COMMENT ON COLUMN "MEMBER"."SET_AL_TAG" IS '태그알림(N:OFF, Y:ON)';
COMMENT ON COLUMN "MEMBER"."SET_AL_REPLY" IS '게시글댓글알림(N:OFF, Y:ON)';
COMMENT ON COLUMN "MEMBER"."SET_AL_LIKE" IS '게시글좋아요알림(N:OFF, Y:ON)';
COMMENT ON COLUMN "MEMBER"."SET_AL_SHARE" IS '게시글공유알림(N:OFF, Y:ON)';
COMMENT ON COLUMN "MEMBER"."SET_AL_FEED" IS '개인피드갱신알림(N:OFF, Y:ON)';

-- 기본키 설정
ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_NO");

-- "MEMBER" CHECK 제약조건 추가
ALTER TABLE "MEMBER" ADD CONSTRAINT "CHK_MEMBER_CODE" CHECK(MEMBER_CODE IN('A', 'N', 'B', 'D'));
ALTER TABLE "MEMBER" ADD CONSTRAINT "CHK_SET_FRIEND_REQ" CHECK(SET_FRIEND_REQ IN('N', 'Y'));
ALTER TABLE "MEMBER" ADD CONSTRAINT "CHK_SET_FEED_AUTH" CHECK(SET_FEED_AUTH IN('N', 'Y'));
ALTER TABLE "MEMBER" ADD CONSTRAINT "CHK_SET_AL_FRIEND_REQ" CHECK(SET_AL_FRIEND_REQ IN('N', 'Y'));
ALTER TABLE "MEMBER" ADD CONSTRAINT "CHK_SET_AL_REQ_ACCEPT" CHECK(SET_AL_REQ_ACCEPT IN('N', 'Y'));
ALTER TABLE "MEMBER" ADD CONSTRAINT "CHK_SET_AL_TAG" CHECK(SET_AL_TAG IN('N', 'Y'));
ALTER TABLE "MEMBER" ADD CONSTRAINT "CHK_SET_AL_REPLY" CHECK(SET_AL_REPLY IN('N', 'Y'));
ALTER TABLE "MEMBER" ADD CONSTRAINT "CHK_SET_AL_LIKE" CHECK(SET_AL_LIKE IN('N', 'Y'));
ALTER TABLE "MEMBER" ADD CONSTRAINT "CHK_SET_AL_SHARE" CHECK(SET_AL_SHARE IN('N', 'Y'));
ALTER TABLE "MEMBER" ADD CONSTRAINT "CHK_SET_AL_FEED" CHECK(SET_AL_FEED IN('N', 'Y'));

-- SEQ_MEMBER_NO 시퀀스 생성
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

-- "MEMBER" 관리자 데이터 삽입
INSERT INTO "MEMBER" 
VALUES(
	SEQ_MEMBER_NO.NEXTVAL, 	-- 회원번호
	'admin', 				-- 이메일
	'admin', 				-- 비밀번호
	'관리자', 				-- 이름
	'01000000000',			-- 전화번호
	'A', 					-- 계정상태(A:관리자, N:정상(기본), B:비활성, D:탈퇴)
	DEFAULT, 				-- 가입일(기본:SYSDATE)
	NULL, 					-- 비활성화일
	NULL, 					-- 탈퇴일
	DEFAULT, 				-- 친구요청(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 개인피드설정(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 친구요청알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 친구신청수락알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 태그알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 게시글댓글알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 게시글좋아요알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 게시글공유알림(N:OFF, Y:ON(기본))
	DEFAULT					-- 개인피드갱신알림(N:OFF, Y:ON(기본))
);

COMMIT;

-- "MEMBER" 일반유저 데이터 삽입
INSERT INTO "MEMBER" 
VALUES(
	SEQ_MEMBER_NO.NEXTVAL, 	-- 회원번호
	'user01@mail.com', 		-- 이메일
	'pass01', 				-- 비밀번호
	'유저일', 				-- 이름
	'01011112222',			-- 전화번호
	DEFAULT, 				-- 계정상태(A:관리자, N:정상(기본), B:비활성, D:탈퇴)
	DEFAULT, 				-- 가입일(기본:SYSDATE)
	NULL, 					-- 비활성화일
	NULL, 					-- 탈퇴일
	DEFAULT, 				-- 친구요청(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 개인피드설정(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 친구요청알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 친구신청수락알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 태그알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 게시글댓글알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 게시글좋아요알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 게시글공유알림(N:OFF, Y:ON(기본))
	DEFAULT					-- 개인피드갱신알림(N:OFF, Y:ON(기본))
);

COMMIT;

----------------------------------------------------------------------------------------

SELECT * FROM "MEMBER";